//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int Employee_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Street_Address { get; set; }
        public string Town_Address { get; set; }
        public string County_Address { get; set; }
        public string Education { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> Accesslevel { get; set; }
    
        public virtual Access Access { get; set; }
    }
}
