//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.HISTORies = new HashSet<HISTORY>();
        }
    
        public int ItemID { get; set; }
        public Nullable<int> ISBN { get; set; }
        public Nullable<int> DVDNo { get; set; }
        public Nullable<int> JournalNo { get; set; }
        public Nullable<int> ConferenceNo { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Charge { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual CONFERENCEPROCEEDING CONFERENCEPROCEEDING { get; set; }
        public virtual DVD DVD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY> HISTORies { get; set; }
        public virtual JOURNAL JOURNAL { get; set; }
        public virtual Member Member { get; set; }
    }
}
