//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBEntities : DbContext
    {
        public LibraryDBEntities()
            : base("name=LibraryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Accesses { get; set; }
        public virtual DbSet<BOOK> BOOKs { get; set; }
        public virtual DbSet<CONFERENCEPROCEEDING> CONFERENCEPROCEEDINGs { get; set; }
        public virtual DbSet<DVD> DVDs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<HISTORY> HISTORies { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<JOURNAL> JOURNALs { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MEMBERHISTORY> MEMBERHISTORies { get; set; }
        public virtual DbSet<ptemp3> ptemp3 { get; set; }
        public virtual DbSet<PUBLISHER> PUBLISHERs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SYSLOG> SYSLOGs { get; set; }
        public virtual DbSet<TRANSACTION> TRANSACTIONS { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
