//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptemp3
    {
        public string OrganisationName { get; set; }
        public string SubBuildingName { get; set; }
        public string BuildingName { get; set; }
        public string Number { get; set; }
        public string PrimaryThorfare { get; set; }
        public string SecondaryThorfare { get; set; }
        public string AltThorfare { get; set; }
        public string Locality { get; set; }
        public string Townland { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Xcoordinates { get; set; }
        public string Ycoordinates { get; set; }
        public int PostID { get; set; }
    }
}
