//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public int TransactionNo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> CostAmount { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public Nullable<int> Publisher_ID { get; set; }
    
        public virtual PUBLISHER PUBLISHER { get; set; }
    }
}
